[project]
name = "the-snoopy-agent-experience"
version = "0.1.0"
description = "An Agent that snoops"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel",
	"langchain",
    "langchain-community",
    "langchain-ollama",
]
